name: goshare custom tag and release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Custom release tag
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set tag
        run: |
          echo "Tag for release is ${{ inputs.release_tag }}"
          echo "tag=${{ inputs.release_tag }}" >> ${GITHUB_ENV}         
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install dependencies
        run: |
          export PATH=$PWD/bin:$PATH
          task install
          task build
          task build-arm
          task run

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: goshare ${{ env.tag }}
          tag_name: ${{ env.tag }}
          body: "goshare release ${{ env.tag }}"
          files: |
            bin/server
            bin/client
            bin/wait-fs
            bin/wait
            bin/server-arm
            bin/client-arm
            bin/wait-fs-arm
            bin/wait-arm
        env:
          GITHUB_REPOSITORY: converged-computing/goshare
